using System.IO;
using System.Text;
using StreamOrchestra.App.Models;

namespace StreamOrchestra.App.Services;

public sealed class ExternalBrowserLaunchScriptService
{
    private static readonly StreamNavigationService NavigationService = new();

    public string SaveScript(ExternalBrowserFallbackPlan plan, string dataFolder, DateTimeOffset generatedAt)
    {
        Directory.CreateDirectory(dataFolder);
        var path = Path.Combine(dataFolder, $"external-browser-fallback-{generatedAt:yyyyMMdd-HHmmss}.ps1");
        File.WriteAllText(path, CreateScript(plan), Encoding.UTF8);

        return path;
    }

    public string CreateScript(ExternalBrowserFallbackPlan plan)
    {
        if (plan is null)
        {
            throw new ArgumentNullException(nameof(plan));
        }

        if (!plan.CanLaunch)
        {
            throw new InvalidOperationException($"Cannot create an external browser fallback script: {plan.Reason}");
        }

        var scriptSlots = NormalizeScriptSlots(plan.Slots);
        if (scriptSlots.Length == 0)
        {
            throw new InvalidOperationException("Cannot create an external browser fallback script: no launchable slot plan is available.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Stream Orchestra.");
        builder.AppendLine("# Review before running. This launches normal browsers with isolated user data folders.");
        builder.AppendLine($"# Plan: {ToCommentText(plan.Reason)}");
        builder.AppendLine($"# Installed browser candidates: {plan.InstalledBrowserCount}");
        builder.AppendLine($"# Planned slots: {scriptSlots.Length}");
        builder.AppendLine("$ErrorActionPreference = 'Stop'");
        builder.AppendLine();

        if (scriptSlots.Any(slot => slot.WindowLayout is not null))
        {
            AppendWindowLayoutHelpers(builder);
        }

        foreach (var slot in scriptSlots.OrderBy(slot => slot.SlotId))
        {
            builder.AppendLine($"# Slot {slot.SlotId}: {ToCommentText(slot.StreamName)}");
            builder.AppendLine($"# Browser: {ToCommentText(slot.BrowserName)} ({ToCommentText(slot.BrowserId)})");
            builder.AppendLine($"# Executable: {ToCommentText(slot.ExecutablePath)}");
            builder.AppendLine($"# Profile: {ToCommentText(slot.UserDataFolder)}");
            builder.AppendLine($"# URL: {ToCommentText(slot.StreamUrl)}");
            builder.AppendLine($"# Muted: {slot.IsMuted}");
            builder.AppendLine($"New-Item -ItemType Directory -Force -Path {ToPowerShellString(slot.UserDataFolder)} | Out-Null");
            if (slot.WindowLayout is not null)
            {
                AppendWindowBoundsCommand(builder, slot.WindowLayout);
            }

            builder.AppendLine("$arguments = @(");

            var arguments = slot.Arguments
                .Select(argument => ToPowerShellString(ToBrowserCommandLineArgument(argument)))
                .ToList();
            if (slot.WindowLayout is not null)
            {
                arguments.Add("\"--window-position=$($slotWindow.Left),$($slotWindow.Top)\"");
                arguments.Add("\"--window-size=$($slotWindow.Width),$($slotWindow.Height)\"");
            }

            for (var index = 0; index < arguments.Count; index++)
            {
                var suffix = index == arguments.Count - 1 ? "" : ",";
                builder.AppendLine($"    {arguments[index]}{suffix}");
            }

            builder.AppendLine(")");
            builder.AppendLine($"$process = Start-Process -FilePath {ToPowerShellString(slot.ExecutablePath)} -ArgumentList $arguments -PassThru");
            if (slot.WindowLayout is not null)
            {
                builder.AppendLine("Move-StreamOrchestraBrowserWindow -Process $process -Bounds $slotWindow");
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static ExternalBrowserSlotLaunchPlan[] NormalizeScriptSlots(
        IReadOnlyList<ExternalBrowserSlotLaunchPlan>? slots)
    {
        IEnumerable<ExternalBrowserSlotLaunchPlan?> sourceSlots = slots ?? [];
        return sourceSlots
            .Select(NormalizeScriptSlot)
            .Where(slot => slot is not null)
            .Select(slot => slot!)
            .ToArray();
    }

    private static ExternalBrowserSlotLaunchPlan? NormalizeScriptSlot(ExternalBrowserSlotLaunchPlan? slot)
    {
        if (slot is null ||
            slot.SlotId is < 1 or > PlaybackTestPlanService.MaxSlotCount ||
            string.IsNullOrWhiteSpace(slot.ExecutablePath) ||
            string.IsNullOrWhiteSpace(slot.UserDataFolder))
        {
            return null;
        }

        var streamUrl = NavigationService.NormalizeUrl(slot.StreamUrl ?? "");
        if (streamUrl.Equals("about:blank", StringComparison.OrdinalIgnoreCase) ||
            !Uri.TryCreate(streamUrl, UriKind.Absolute, out var uri) ||
            uri.Scheme is not ("http" or "https"))
        {
            return null;
        }

        var userDataFolder = slot.UserDataFolder.Trim();
        var browserId = string.IsNullOrWhiteSpace(slot.BrowserId)
            ? "browser"
            : slot.BrowserId.Trim();
        var browserName = string.IsNullOrWhiteSpace(slot.BrowserName)
            ? browserId
            : slot.BrowserName.Trim();
        var streamName = string.IsNullOrWhiteSpace(slot.StreamName)
            ? NavigationService.CreateDisplayName(streamUrl)
            : slot.StreamName.Trim();
        var arguments = NormalizeArguments(userDataFolder, streamUrl, slot.IsMuted);

        return new ExternalBrowserSlotLaunchPlan(
            slot.SlotId,
            streamName,
            streamUrl,
            browserId,
            browserName,
            slot.ExecutablePath.Trim(),
            userDataFolder,
            arguments,
            IsValidWindowLayout(slot.WindowLayout) ? slot.WindowLayout : null,
            slot.IsMuted);
    }

    private static IReadOnlyList<string> NormalizeArguments(
        string userDataFolder,
        string streamUrl,
        bool isMuted)
    {
        var arguments = new List<string>
        {
            $"--user-data-dir={userDataFolder}",
            "--new-window"
        };

        if (isMuted)
        {
            arguments.Add("--mute-audio");
        }

        arguments.Add(streamUrl);
        return arguments;
    }

    private static bool IsValidWindowLayout(ExternalBrowserWindowLayout? layout)
    {
        return layout is
        {
            GridColumns: > 0,
            GridRows: > 0,
            X: >= 0,
            Y: >= 0,
            W: > 0,
            H: > 0
        } &&
            layout.X + layout.W <= layout.GridColumns &&
            layout.Y + layout.H <= layout.GridRows;
    }

    private static void AppendWindowLayoutHelpers(StringBuilder builder)
    {
        builder.AppendLine("Add-Type -AssemblyName System.Windows.Forms");
        builder.AppendLine("if (-not ('StreamOrchestraWindowTools' -as [type])) {");
        builder.AppendLine("Add-Type @'");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.InteropServices;");
        builder.AppendLine("public static class StreamOrchestraWindowTools");
        builder.AppendLine("{");
        builder.AppendLine("    [DllImport(\"user32.dll\")]");
        builder.AppendLine("    public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags);");
        builder.AppendLine("}");
        builder.AppendLine("'@");
        builder.AppendLine("}");
        builder.AppendLine("function Get-StreamOrchestraSlotWindowBounds {");
        builder.AppendLine("    param(");
        builder.AppendLine("        [int]$GridColumns,");
        builder.AppendLine("        [int]$GridRows,");
        builder.AppendLine("        [int]$CellX,");
        builder.AppendLine("        [int]$CellY,");
        builder.AppendLine("        [int]$CellWidth,");
        builder.AppendLine("        [int]$CellHeight,");
        builder.AppendLine("        [double[]]$ColumnWeights = @(),");
        builder.AppendLine("        [double[]]$RowWeights = @()");
        builder.AppendLine("    )");
        builder.AppendLine("    $workArea = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea");
        builder.AppendLine("    $columnWeights = Get-StreamOrchestraGridWeights -Count $GridColumns -Weights $ColumnWeights");
        builder.AppendLine("    $rowWeights = Get-StreamOrchestraGridWeights -Count $GridRows -Weights $RowWeights");
        builder.AppendLine("    $columnTotal = Get-StreamOrchestraWeightSum -Weights $columnWeights -Start 0 -Length $GridColumns");
        builder.AppendLine("    $rowTotal = Get-StreamOrchestraWeightSum -Weights $rowWeights -Start 0 -Length $GridRows");
        builder.AppendLine("    $leftWeight = Get-StreamOrchestraWeightSum -Weights $columnWeights -Start 0 -Length $CellX");
        builder.AppendLine("    $topWeight = Get-StreamOrchestraWeightSum -Weights $rowWeights -Start 0 -Length $CellY");
        builder.AppendLine("    $widthWeight = Get-StreamOrchestraWeightSum -Weights $columnWeights -Start $CellX -Length $CellWidth");
        builder.AppendLine("    $heightWeight = Get-StreamOrchestraWeightSum -Weights $rowWeights -Start $CellY -Length $CellHeight");
        builder.AppendLine("    [pscustomobject]@{");
        builder.AppendLine("        Left = [int]($workArea.Left + ($workArea.Width * $leftWeight / $columnTotal))");
        builder.AppendLine("        Top = [int]($workArea.Top + ($workArea.Height * $topWeight / $rowTotal))");
        builder.AppendLine("        Width = [int]($workArea.Width * $widthWeight / $columnTotal)");
        builder.AppendLine("        Height = [int]($workArea.Height * $heightWeight / $rowTotal)");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("function Get-StreamOrchestraGridWeights {");
        builder.AppendLine("    param([int]$Count, [double[]]$Weights)");
        builder.AppendLine("    $values = @()");
        builder.AppendLine("    for ($index = 0; $index -lt $Count; $index++) {");
        builder.AppendLine("        $value = 1.0");
        builder.AppendLine("        if ($Weights -and $Weights.Length -eq $Count -and $Weights[$index] -gt 0) { $value = [double]$Weights[$index] }");
        builder.AppendLine("        $values += $value");
        builder.AppendLine("    }");
        builder.AppendLine("    return ,$values");
        builder.AppendLine("}");
        builder.AppendLine("function Get-StreamOrchestraWeightSum {");
        builder.AppendLine("    param([double[]]$Weights, [int]$Start, [int]$Length)");
        builder.AppendLine("    $sum = 0.0");
        builder.AppendLine("    for ($index = $Start; $index -lt ($Start + $Length) -and $index -lt $Weights.Length; $index++) {");
        builder.AppendLine("        if ($index -ge 0) { $sum += [double]$Weights[$index] }");
        builder.AppendLine("    }");
        builder.AppendLine("    return $sum");
        builder.AppendLine("}");
        builder.AppendLine("function Move-StreamOrchestraBrowserWindow {");
        builder.AppendLine("    param(");
        builder.AppendLine("        [System.Diagnostics.Process]$Process,");
        builder.AppendLine("        [pscustomobject]$Bounds");
        builder.AppendLine("    )");
        builder.AppendLine("    for ($attempt = 0; $attempt -lt 50 -and $Process.MainWindowHandle -eq 0; $attempt++) {");
        builder.AppendLine("        Start-Sleep -Milliseconds 200");
        builder.AppendLine("        $Process.Refresh()");
        builder.AppendLine("    }");
        builder.AppendLine("    if ($Process.MainWindowHandle -eq 0) { return }");
        builder.AppendLine("    [StreamOrchestraWindowTools]::SetWindowPos($Process.MainWindowHandle, [IntPtr]::Zero, $Bounds.Left, $Bounds.Top, $Bounds.Width, $Bounds.Height, 0x0040) | Out-Null");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendWindowBoundsCommand(StringBuilder builder, ExternalBrowserWindowLayout layout)
    {
        builder.AppendLine(
            $"$slotWindow = Get-StreamOrchestraSlotWindowBounds -GridColumns {layout.GridColumns} -GridRows {layout.GridRows} -CellX {layout.X} -CellY {layout.Y} -CellWidth {layout.W} -CellHeight {layout.H} -ColumnWeights {ToPowerShellDoubleArray(layout.ColumnWeights, layout.GridColumns)} -RowWeights {ToPowerShellDoubleArray(layout.RowWeights, layout.GridRows)}");
    }

    private static string ToPowerShellDoubleArray(IReadOnlyList<double>? weights, int expectedCount)
    {
        if (weights is null || weights.Count != expectedCount || weights.Any(weight => weight <= 0 || double.IsNaN(weight) || double.IsInfinity(weight)))
        {
            return "@()";
        }

        return $"@({string.Join(", ", weights.Select(weight => weight.ToString("G17", System.Globalization.CultureInfo.InvariantCulture)))})";
    }

    private static string ToBrowserCommandLineArgument(string argument)
    {
        if (argument is "--new-window" or "--mute-audio")
        {
            return argument;
        }

        return $"\"{argument.Replace("\"", "\\\"")}\"";
    }

    private static string ToPowerShellString(string value)
    {
        return $"'{value.Replace("'", "''")}'";
    }

    private static string ToCommentText(string? value)
    {
        return (value ?? "").Replace('\r', ' ').Replace('\n', ' ');
    }
}
